export const tagConfig = {
    title: 'Tags',
    descriptionUpdate: 'Update your tag',
    description: 'Manage your tags',
    delete: 'Delete',
    edit: 'Edit',
    update: 'Update',
    questionDelete: 'Are you sure you want to delete this tag?',
    warning: 'This action cannot be undone.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    tableHeader: ['Tag', 'Date', 'Action'],
    updatetag: 'Update tag',
    newtag: 'New tag',
    successDelete: 'tag deleted.',
    successCreate: 'tag created.',
    successUpdate: 'tag updated.',
    errorCreate: "Couldn't create tag.",
    errorDelete: "Couldn't delete tag.",
    errorUpdate: "Couldn't update tag.",
    author: 'Author',
    pleaseWait: 'Please wait...',
    untitled: 'Untitled',
}